# Generated by Django 2.1.2 on 2019-09-12 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_userprofile_suggested_shows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.TvShow')),
                ('suggested_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_shows',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_shows',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.TvShow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='suggested_shows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Suggestion'),
        ),
    ]
