# Generated by Django 2.1.2 on 2019-09-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190912_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_shows',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_shows',
            field=models.ManyToManyField(blank=True, to='users.TvShow'),
        ),
    ]
