# Generated by Django 2.1.2 on 2019-09-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190912_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='suggested_shows',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suggested_shows',
            field=models.ManyToManyField(blank=True, to='users.Suggestion'),
        ),
    ]
