# Generated by Django 2.1.2 on 2019-09-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190914_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='tv_id',
            field=models.FloatField(default=0),
        ),
    ]
